# -*- coding: utf-8 -*-
"""Wheat6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nPO5vGwNS03Yv8intcAMiVs57Q_NePd6
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

df = pd.read_csv('wheat.txt', header=None, delimiter='\t+', engine="python")
df

X_train, X_test, y_train, y_test = train_test_split(df[[0,1,2,3,4,5,6]],df[7], test_size=0.3)

# Define the classifier using kNN function and train it
classifier = KNeighborsClassifier(n_neighbors=3)
classifier.fit(X_train,y_train)

# Test the classifier by giving it test instances
prediction = classifier.predict(X_test)

# Count how many were correctly classified
correct = np.where(prediction==y_test, 1, 0).sum()
print(correct)

accuracy = correct/len(y_test)
print(accuracy)

results = []

for k in range(1, 51, 2):
  classifier = KNeighborsClassifier(n_neighbors=k)
  classifier.fit(X_train,y_train)
  prediction = classifier.predict(X_test)
  correct = np.where(prediction==y_test, 1, 0).sum()
  accuracy = correct/len(y_test)
  print ("k=", k, " Accuracy=", accuracy)
  results.append([k,accuracy])

# Convert that series of tuples in a dataframe for easy plotting
results = pd.DataFrame(results, columns=["k","accuracy"])

plt.plot(results.k, results.accuracy)
plt.title("Value of k and corresponding classification accuracy")
plt.show()